from __future__ import division
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine('postgresql://nfldb@localhost:5432/nfldb')

# load passing_df
passing_df = pd.read_sql_query("SELECT game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position, SUM(play_player.passing_att) AS passing_att, SUM(play_player.passing_cmp) AS passing_cmp, SUM(play_player.passing_yds) AS passing_yds, SUM(play_player.passing_int) AS passing_int, SUM(play_player.passing_tds) AS passing_tds, SUM(play_player.passing_twopta) AS passing_twopta, SUM(play_player.passing_twoptm) AS passing_twoptm, SUM(play_player.receiving_rec) AS receiving_rec, SUM(play_player.receiving_tar) AS receiving_tar, SUM(play_player.receiving_tds) AS receiving_tds, SUM(play_player.receiving_twopta) AS receiving_twopta, SUM(play_player.receiving_twoptm) AS receiving_twoptm, SUM(play_player.receiving_yac_yds) AS receiving_yac, SUM(play_player.receiving_yds) AS receiving_yds, SUM(play_player.rushing_att) AS rushing_att, SUM(play_player.rushing_yds) AS rushing_yds, SUM(play_player.rushing_tds) AS rushing_tds, SUM(play_player.rushing_loss_yds) AS rushing_loss_yards, SUM(play_player.rushing_twoptm) AS rushing_twoptm, SUM(play_player.fumbles_tot) AS fumbles_total, SUM(play_player.fumbles_rec_tds) AS fumble_rec_tds FROM play_player JOIN player ON player.player_id = play_player.player_id JOIN game ON game.gsis_id = play_player.gsis_id WHERE player.position = 'QB' GROUP BY game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position HAVING SUM(play_player.passing_att) > 0 ORDER BY game.season_year DESC, game.week ASC", con=engine)

# load receiving df
receiving_df = pd.read_sql_query("SELECT game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position, SUM(play_player.receiving_rec) AS receiving_rec, SUM(play_player.receiving_tar) AS receiving_tar, SUM(play_player.receiving_tds) AS receiving_tds, SUM(play_player.receiving_twopta) AS receiving_twopta, SUM(play_player.receiving_twoptm) AS receiving_twoptm, SUM(play_player.receiving_yac_yds) AS receiving_yac, SUM(play_player.receiving_yds) AS receiving_yds, SUM(play_player.fumbles_tot) AS fumbles_total, SUM(play_player.fumbles_rec_tds) AS fumble_rec_tds, SUM(play_player.kicking_rec_tds) AS kicking_rec_tds, SUM(play_player.puntret_tds) AS punt_ret_tds, SUM(play_player.rushing_att) AS rushing_att, SUM(play_player.rushing_yds) AS rushing_yds, SUM(play_player.rushing_tds) AS rushing_tds, SUM(play_player.rushing_loss_yds) AS rushing_loss_yards, SUM(play_player.rushing_twoptm) AS rushing_twoptm FROM play_player JOIN player ON player.player_id = play_player.player_id JOIN game on game.gsis_id = play_player.gsis_id WHERE player.position = 'WR' GROUP BY game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position HAVING SUM(play_player.receiving_rec) > 0 ORDER BY game.season_year DESC, game.week ASC", con=engine)

# load rushing df
rushing_df = pd.read_sql_query("SELECT game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position, SUM(play_player.receiving_rec) AS receiving_rec, SUM(play_player.receiving_tar) AS receiving_tar, SUM(play_player.receiving_tds) AS receiving_tds, SUM(play_player.receiving_twopta) AS receiving_twopta, SUM(play_player.receiving_twoptm) AS receiving_twoptm, SUM(play_player.receiving_yac_yds) AS receiving_yac, SUM(play_player.receiving_yds) AS receiving_yds, SUM(play_player.fumbles_tot) AS fumbles_total, SUM(play_player.fumbles_rec_tds) AS fumble_rec_tds, SUM(play_player.kicking_rec_tds) AS kicking_rec_tds, SUM(play_player.puntret_tds) AS punt_ret_tds, SUM(play_player.rushing_att) AS rushing_att, SUM(play_player.rushing_yds) AS rushing_yds, SUM(play_player.rushing_tds) AS rushing_tds, SUM(play_player.rushing_loss_yds) AS rushing_loss_yards, SUM(play_player.rushing_twoptm) AS rushing_twoptm FROM play_player JOIN player ON player.player_id = play_player.player_id JOIN game on game.gsis_id = play_player.gsis_id WHERE player.position = 'RB' GROUP BY game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position HAVING SUM(play_player.receiving_rec) > 0 ORDER BY game.season_year DESC, game.week ASC", con = engine)

# load tight end DF
tight_end_df = pd.read_sql_query("SELECT game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position, SUM(play_player.receiving_rec) AS receiving_rec, SUM(play_player.receiving_tar) AS receiving_tar, SUM(play_player.receiving_tds) AS receiving_tds, SUM(play_player.receiving_twopta) AS receiving_twopta, SUM(play_player.receiving_twoptm) AS receiving_twoptm, SUM(play_player.receiving_yac_yds) AS receiving_yac, SUM(play_player.receiving_yds) AS receiving_yds, SUM(play_player.fumbles_tot) AS fumbles_total, SUM(play_player.fumbles_rec_tds) AS fumble_rec_tds, SUM(play_player.kicking_rec_tds) AS kicking_rec_tds, SUM(play_player.puntret_tds) AS punt_ret_tds, SUM(play_player.rushing_att) AS rushing_att, SUM(play_player.rushing_yds) AS rushing_yds, SUM(play_player.rushing_tds) AS rushing_tds, SUM(play_player.rushing_loss_yds) AS rushing_loss_yards, SUM(play_player.rushing_twoptm) AS rushing_twoptm FROM play_player JOIN player ON player.player_id = play_player.player_id JOIN game on game.gsis_id = play_player.gsis_id WHERE player.position = 'TE' GROUP BY game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, player.team, player.full_name, player.position HAVING SUM(play_player.receiving_rec) > 0 ORDER BY game.season_year DESC, game.week ASC", con=engine)

# load defense DF
defense_df = pd.read_sql_query("SELECT game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, play_player.team, SUM(play_player.defense_ffum) AS forced_fumble, SUM(play_player.defense_fgblk) AS fg_block, SUM(play_player.defense_frec) AS fumble_rec, SUM(play_player.defense_frec_tds) AS fumble_rec_tds, SUM(play_player.defense_int) AS ints, SUM(play_player.defense_int_tds) AS int_tds, SUM(play_player.defense_misc_tds) AS misc_tds, SUM(play_player.defense_puntblk) AS punt_block, SUM(play_player.defense_safe) AS safety, SUM(play_player.defense_sk) AS sack, SUM(play_player.defense_xpblk) AS xp_block FROM play_player JOIN game ON play_player.gsis_id = game.gsis_id JOIN player ON play_player.player_id = player.player_id GROUP BY game.season_year, game.season_type, game.week, game.home_team, game.home_score, game.away_team, game.away_score, play_player.team ORDER BY game.season_year DESC, game.week ASC", con=engine)



if __name__ == '__main__':

    passing_df.to_csv('/Users/MACDaddy/fantasy_football/NFL_things/nfldb_queries/Data/passing_df.csv')
    receiving_df.to_csv('/Users/MACDaddy/fantasy_football/NFL_things/nfldb_queries/Data/receiving_df.csv')
    rushing_df.to_csv('/Users/MACDaddy/fantasy_football/NFL_things/nfldb_queries/Data/rushing_df.csv')
    tight_end_df.to_csv('/Users/MACDaddy/fantasy_football/NFL_things/nfldb_queries/Data/tight_end_df.csv')
    defense_df.to_csv('/Users/MACDaddy/fantasy_football/NFL_things/nfldb_queries/Data/defense_df.csv')
